
[Executed at: Sun Mar 18 23:53:18 PDT 2018]

Traceback (most recent call last):
  File "/home/ccc_v1_c79523__48809/asn24778_45/asn24779_1/asnlib/autograde.py", line 14, in <module>
    score=runtest.main()
  File "/home/ccc_v1_c79523__48809/asn24778_45/asn24779_1/asnlib/runtestcases.py", line 63, in main
    stu_work=getattr(__import__(work_package, fromlist=fun_name), f)
  File "./q3_work.py", line 18, in <module>
    print(vol_frustum(1,4,2))
  File "./q3_work.py", line 9, in vol_frustum
    vo=(height/3)(top_area+bottom_area+math.sqrt(top_area*bottom_area))
TypeError: 'float' object is not callable
Command exited with non-zero status 1
